// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/credanta-ui/DesktopDashboard.tsx": () => import("../components/mockups/credanta-ui/DesktopDashboard.tsx"),
  "./components/mockups/credanta-ui/MobileDashboard.tsx": () => import("../components/mockups/credanta-ui/MobileDashboard.tsx"),
  "./components/mockups/credanta-ui/PremiumPage.tsx": () => import("../components/mockups/credanta-ui/PremiumPage.tsx")
};
